
package vistas;

import combos.ClienteCombo_1;

import combos.VenderCombo_1;
import consultas.ConsultasCliente;
import consultas.ConsultasStockGas;
import consultas.ConsultasVender;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Boleta;
import modelo.Cliente;
import modelo.DetalleCompra;
import modelo.StockGas;


public class Vender extends javax.swing.JFrame {

    Boleta bo = new Boleta();
    Cliente clie = new Cliente();
    StockGas stk = new StockGas();
    DetalleCompra dc = new DetalleCompra();
    ConsultasStockGas cstk = new ConsultasStockGas();
    ConsultasVender cv = new ConsultasVender();
    ConsultasCliente clv = new ConsultasCliente();
    DefaultTableModel gases = new DefaultTableModel();

    double totalPagar;

    public Vender() {
        initComponents();
        actualizarCombo();

        Calendar calendar = new GregorianCalendar();
        xfecha.setText("" + calendar.get(Calendar.YEAR) + "-" + calendar.get(Calendar.MAY) + "-" + calendar.get(Calendar.DAY_OF_MONTH));

    }

    void actualizarCombo() {
        ClienteCombo_1.conectar();
        xrunC.removeAllItems();
        ArrayList<String> lista = new ArrayList<String>();
        lista = ClienteCombo_1.llenar_combox();
        for (int i = 0; i < lista.size(); i++) {
            xrunC.addItem(lista.get(i));
        }
    }
    void actualizarComboGas() {
        VenderCombo_1.conectar();
        xgasito.removeAllItems();
        ArrayList<String> lista = new ArrayList<String>();
        lista = VenderCombo_1.llenar_comboxs();
        for (int i = 0; i < lista.size(); i++) {
            xgasito.addItem(lista.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        xnombreclienteG = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        xcomunaC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        xrunC = new javax.swing.JComboBox<>();
        xnumeroC = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        xdirecionC = new javax.swing.JTextField();
        agregarC = new javax.swing.JButton();
        xIDC = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        xcodigoPago = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        xstockG = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        xnombreG = new javax.swing.JTextField();
        xtipogasG = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        xprecioG = new javax.swing.JTextField();
        xgasito = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        x45 = new javax.swing.JSpinner();
        x15 = new javax.swing.JSpinner();
        x11 = new javax.swing.JSpinner();
        x5 = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        xtotalPagar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        xtablaVenta = new javax.swing.JTable();
        x45total = new javax.swing.JTextField();
        x15total = new javax.swing.JTextField();
        x11total = new javax.swing.JTextField();
        x5total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        xfecha = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("Nombre Cliente:");

        jLabel2.setText("RUN Cliente:");

        xnombreclienteG.setEditable(false);

        jLabel3.setText("Numero Telefono:");

        jLabel4.setText("Comuna:");

        xcomunaC.setEditable(false);
        xcomunaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xcomunaCActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        xrunC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xrunCActionPerformed(evt);
            }
        });

        xnumeroC.setEditable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton5.setText("NUEVO CLIENTE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(28, 28, 28))
        );

        jLabel13.setText("Direccion:");

        xdirecionC.setEditable(false);

        agregarC.setText("AGREGAR");
        agregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCActionPerformed(evt);
            }
        });

        xIDC.setEditable(false);
        xIDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xIDCActionPerformed(evt);
            }
        });

        jLabel18.setText("ID Cliente:");

        jLabel20.setText("METODO PAGO");

        xcodigoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Debito", "Tarjeta/Credito" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xrunC, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(xcodigoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(agregarC))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel13)
                            .addComponent(jLabel4)
                            .addComponent(jLabel18))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xIDC)
                    .addComponent(xnombreclienteG)
                    .addComponent(xnumeroC)
                    .addComponent(xcomunaC)
                    .addComponent(xdirecionC, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(xrunC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agregarC))
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(xIDC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(xnombreclienteG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(xcomunaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(xnumeroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(xdirecionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(xcodigoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gas.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel9.setText("TIPO GAS");

        jLabel10.setText("Stock:");

        xstockG.setEditable(false);

        jButton4.setText("AGREGAR A LA LISTA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setText("Nombre:");

        xnombreG.setEditable(false);

        xtipogasG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "45", "15", "11", "5" }));
        xtipogasG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtipogasGActionPerformed(evt);
            }
        });

        jLabel12.setText("Precio:");

        xprecioG.setEditable(false);

        xgasito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xgasitoActionPerformed(evt);
            }
        });

        jLabel14.setText("ID GAS");

        x45.setModel(new javax.swing.SpinnerNumberModel());
        x45.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        x45.setEnabled(false);
        x45.setFocusable(false);
        x45.setOpaque(false);

        x15.setEnabled(false);
        x15.setFocusable(false);

        x11.setEnabled(false);
        x11.setFocusable(false);

        x5.setEnabled(false);
        x5.setFocusable(false);

        jLabel21.setText("Cantidades de cada tipo de GAS");

        jLabel22.setText("45");

        jLabel23.setText("15");

        jLabel24.setText("11");

        jLabel25.setText("5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addComponent(x45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(x15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(x11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(xgasito, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(xtipogasG, 0, 113, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(23, 23, 23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(xnombreG, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(xstockG, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(xprecioG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(xnombreG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(xstockG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(xprecioG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(xtipogasG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(xgasito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(x45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 13, Short.MAX_VALUE))))
        );

        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("GENERAR VENTA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        xtotalPagar.setEditable(false);
        xtotalPagar.setText("0");

        jLabel5.setText("MONTO TOTAL:");

        xtablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro", "ID", "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        xtablaVenta.setEnabled(false);
        jScrollPane3.setViewportView(xtablaVenta);

        x45total.setEditable(false);
        x45total.setText("0");
        x45total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x45totalActionPerformed(evt);
            }
        });

        x15total.setEditable(false);
        x15total.setText("0");
        x15total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x15totalActionPerformed(evt);
            }
        });

        x11total.setEditable(false);
        x11total.setText("0");

        x5total.setEditable(false);
        x5total.setText("0");

        jLabel8.setText("45KG");

        jLabel15.setText("15KG");

        jLabel16.setText("11KG");

        jLabel17.setText("5KG");

        xfecha.setEditable(false);
        xfecha.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        xfecha.setForeground(new java.awt.Color(51, 51, 255));
        xfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xfechaActionPerformed(evt);
            }
        });

        jLabel19.setText("FECHA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x45total, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(x15total, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 23, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(x11total, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(xfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(x5total, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(xtotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(x45total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x11total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(x15total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(x5total, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xtotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(xfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        agregarGases();
    }//GEN-LAST:event_jButton4ActionPerformed
    void agregarGases() {
        if (!validarTabla()) {
            int item = 0;
            gases = (DefaultTableModel) xtablaVenta.getModel();
            item = item + 1;
            String ID = xgasito.getSelectedItem().toString();
            String Nombre = xnombreG.getText();
            int Precio = Integer.parseInt(xprecioG.getText());
            ArrayList listaG = new ArrayList();
            listaG.add(item);
            listaG.add(ID);
            listaG.add(Nombre);
            listaG.add(Precio);
            Object[] ob = new Object[4];
            ob[0] = listaG.get(0);
            ob[1] = listaG.get(1);
            ob[2] = listaG.get(2);
            ob[3] = listaG.get(3);
            gases.addRow(ob);
            xtablaVenta.setModel(gases);
            cantidad();
            total();
            montoTotal();
        } else {
            JOptionPane.showMessageDialog(null, "GAS YA INGRESADO A LA LISTA,");
        }
    }

    public boolean validarTabla() {
        boolean existe = false;
        for (int i = 0; i < xtablaVenta.getRowCount(); i++) {
            if (xtablaVenta.getValueAt(i, 1).equals(xgasito.getSelectedItem())) {
                existe = true;
            }
        }
        return existe;
    }

    void montoTotal() {
        int total45;
        int total15;
        int total11;
        int total5;
        total45 = Integer.parseInt(x45total.getText());
        total15 = Integer.parseInt(x15total.getText());
        total11 = Integer.parseInt(x11total.getText());
        total5 = Integer.parseInt(x5total.getText());
        int totalVenta = total45 + total15 + total11 + total5;
        xtotalPagar.setText("" + totalVenta);
    }

    void total() {
        String TIPO = xtipogasG.getSelectedItem().toString();
        if (TIPO == "45") {
            int Cantidad45 = Integer.parseInt(x45.getValue().toString());
            int Precio45 = Integer.parseInt(xprecioG.getText());
            int total45 = 0;
            total45 = total45 + (Cantidad45 * Precio45);
            x45total.setText("" + total45);
        }
        if (TIPO == "15") {
            int Cantidad15 = Integer.parseInt(x15.getValue().toString());
            int Precio15 = Integer.parseInt(xprecioG.getText());
            int total15 = 0;
            total15 = total15 + (Cantidad15 * Precio15);
            x15total.setText("" + total15);
        }
        if (TIPO == "11") {
            int Cantidad11 = Integer.parseInt(x11.getValue().toString());
            int Precio11 = Integer.parseInt(xprecioG.getText());
            int total11 = 0;
            total11 = total11 + (Cantidad11 * Precio11);
            x11total.setText("" + total11);
        }
        if (TIPO == "5") {
            int Cantidad5 = Integer.parseInt(x5.getValue().toString());
            int Precio5 = Integer.parseInt(xprecioG.getText());
            int total5 = 0;
            total5 = total5 + (Cantidad5 * Precio5);
            x5total.setText("" + total5);
        }
    }

    void cantidad() {
        try {
            int canti45 = 0;
            int canti15 = 0;
            int canti11 = 0;
            int canti5 = 0;
            String TIPO = xtipogasG.getSelectedItem().toString();
            canti45 = Integer.parseInt(x45.getValue().toString());
            canti15 = Integer.parseInt(x15.getValue().toString());
            canti11 = Integer.parseInt(x11.getValue().toString());
            canti5 = Integer.parseInt(x5.getValue().toString());

            if (TIPO == "45") {
                canti45 = canti45 + 1;
                x45.setValue(+canti45);
            }
            if (TIPO == "15") {
                canti15 = canti15 + 1;
                x15.setValue(+canti15);
            }
            if (TIPO == "11") {
                canti11 = canti11 + 1;
                x11.setValue(+canti11);
            }
            if (TIPO == "5") {;
                canti5 = canti5 + 1;
                x5.setValue(+canti5);
            } else {
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Clientes c = new Clientes();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void xtipogasGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtipogasGActionPerformed
        actualizarComboGas();
        buscarStocks();
    }//GEN-LAST:event_xtipogasGActionPerformed
    void buscarStocks() {
        try {

            stk.setTipo_id(Integer.parseInt(xtipogasG.getSelectedItem().toString()));
            if (cstk.buscarStocks(stk)) {
                xnombreG.setText(stk.getNombre());
                xprecioG.setText("" + stk.getPrecio());
                xstockG.setText("" + stk.getStock());
            }
        } catch (Exception e) {
        }
    }
    private void xgasitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xgasitoActionPerformed

    }//GEN-LAST:event_xgasitoActionPerformed

    private void xrunCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xrunCActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_xrunCActionPerformed

    private void x15totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x15totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x15totalActionPerformed

    private void x45totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x45totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x45totalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (xIDC.getText().length() > 0) {
            if (gases.getRowCount() >= 1) {
                guardarBoleta();
                GuardarDetalleCompra();
                actualizarStockGasVenta5();
                actualizarStockGasVenta11();
                actualizarStockGasVenta15();
                actualizarStockGasVenta45();
                actualizarEstadoGases();
                JOptionPane.showMessageDialog(null, "Pedido realizado con exito");
                limpiarVenta();
            } else {
                JOptionPane.showMessageDialog(null, "Agregue algun gas a la lista porfavor");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un cliente porfavor");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    void actualizarEstadoGases(){
        for (int i = 0; i < xtablaVenta.getRowCount(); i++) {
            int IdG = Integer.parseInt(xtablaVenta.getValueAt(i, 1).toString());
            stk.setId_gas(IdG);
            cstk.actualizarEstadoGases(stk);
        }
    }
    void actualizarStockGasVenta5(){
        int Cantidad = (Integer.parseInt(x5.getValue().toString()));
        stk.setCantidad(Cantidad);
        cstk.actualizarStockGasVenta5(stk);
    }
    void actualizarStockGasVenta11(){
        int Cantidad = (Integer.parseInt(x11.getValue().toString()));
        stk.setCantidad(Cantidad);
        cstk.actualizarStockGasVenta11(stk);
    }
    void actualizarStockGasVenta15(){
        int Cantidad = (Integer.parseInt(x15.getValue().toString()));
        stk.setCantidad(Cantidad);
        cstk.actualizarStockGasVenta15(stk);
    }
    void actualizarStockGasVenta45(){
        int Cantidad = (Integer.parseInt(x45.getValue().toString()));
        stk.setCantidad(Cantidad);
        cstk.actualizarStockGasVenta45(stk);
    }
    void guardarBoleta() {
        String cliente_id = xIDC.getText();
        String monto_total = xtotalPagar.getText();
        String codigo_pago = xcodigoPago.getSelectedItem().toString();
        String estado = "PROCESO";
        String fecha = xfecha.getText();
        bo.setCliente_id(cliente_id);
        bo.setMonto_total(monto_total);
        bo.setCodigo_pago(codigo_pago);
        bo.setEstado(estado);
        bo.setFecha(fecha);
        cv.GuardarBoleta(bo);
    }

    void GuardarDetalleCompra() {
        String idB = cv.IdVentas();
        int idVe = Integer.parseInt(idB);
        for (int i = 0; i < xtablaVenta.getRowCount(); i++) {
            int IdG = Integer.parseInt(xtablaVenta.getValueAt(i, 1).toString());
            int PrecioG = Integer.parseInt(xtablaVenta.getValueAt(i, 3).toString());
            dc.setBoleta_numero(idVe);
            dc.setGas_id(IdG);
            dc.setPrecio(PrecioG);
            cv.GuardarDetalleCompra(dc);
        }
    }

    void limpiarVenta() {
        xnombreclienteG.setText("");
        xIDC.setText("");
        xcomunaC.setText("");
        xdirecionC.setText("");
        xnumeroC.setText("");
        xtipogasG.setSelectedIndex(0);
        xnombreG.setText("");
        xstockG.setText("");
        xprecioG.setText("");
        x5.setValue(0);
        x11.setValue(0);
        x15.setValue(0);
        x45.setValue(0);
        x5total.setText("0");
        x11total.setText("0");
        x15total.setText("0");
        x45total.setText("0");
        xtotalPagar.setText("0");
        gases.setRowCount(0);
    }
    private void xcomunaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xcomunaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xcomunaCActionPerformed

    private void agregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCActionPerformed
        buscarCliente();
    }//GEN-LAST:event_agregarCActionPerformed

    private void xfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xfechaActionPerformed

    private void xIDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xIDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xIDCActionPerformed
    void buscarCliente() {
        clie.setRut_Cliente(xrunC.getSelectedItem().toString());
        if (clv.buscarCliente(clie)) {
            xIDC.setText("" + clie.getId_cliente());
            xnombreclienteG.setText(clie.getNombre());
            xcomunaC.setText("" + clie.getComuna_id());
            xnumeroC.setText(clie.getNumero_Telefono());
            xdirecionC.setText(clie.getDireccion());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JSpinner x11;
    private javax.swing.JTextField x11total;
    private javax.swing.JSpinner x15;
    private javax.swing.JTextField x15total;
    private javax.swing.JSpinner x45;
    private javax.swing.JTextField x45total;
    private javax.swing.JSpinner x5;
    private javax.swing.JTextField x5total;
    private javax.swing.JTextField xIDC;
    private javax.swing.JComboBox<String> xcodigoPago;
    public static javax.swing.JTextField xcomunaC;
    public static javax.swing.JTextField xdirecionC;
    private javax.swing.JTextField xfecha;
    public static javax.swing.JComboBox<String> xgasito;
    public static javax.swing.JTextField xnombreG;
    public static javax.swing.JTextField xnombreclienteG;
    public static javax.swing.JTextField xnumeroC;
    public static javax.swing.JTextField xprecioG;
    public static javax.swing.JComboBox<String> xrunC;
    public static javax.swing.JTextField xstockG;
    private javax.swing.JTable xtablaVenta;
    public static javax.swing.JComboBox<String> xtipogasG;
    private javax.swing.JTextField xtotalPagar;
    // End of variables declaration//GEN-END:variables
}
